# Generated by Django 3.2.13 on 2022-05-05 19:08

import SkillsGuide.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkillsGuide', '0004_alter_text_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=SkillsGuide.utils.Uuid4Upload)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkillsGuide.article')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
